# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'File_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Nova


class UiFileSelect(object):
    def __init__(self):
        self.filePath = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(320, 40, 180, 74))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Title.setSizeIncrement(QtCore.QSize(1, 1))
        self.Title.setStyleSheet("font: 75 33pt \"Ubuntu Condensed\";\n"
                                 "color: rgb(0, 0, 0);\n"
                                 "margin-top: 1ex;")
        self.Title.setScaledContents(True)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.printer = QtWidgets.QLabel(self.centralwidget)
        self.printer.setGeometry(QtCore.QRect(300, 130, 200, 175))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printer.sizePolicy().hasHeightForWidth())
        self.printer.setSizePolicy(sizePolicy)
        self.printer.setMinimumSize(QtCore.QSize(50, 50))
        self.printer.setMaximumSize(QtCore.QSize(200, 200))
        self.printer.setStyleSheet("")
        self.printer.setText("")
        self.printer.setPixmap(QtGui.QPixmap("Resources/Images/3d_logo.png"))
        self.printer.setScaledContents(True)
        self.printer.setAlignment(QtCore.Qt.AlignCenter)
        self.printer.setWordWrap(False)
        self.printer.setIndent(-1)
        self.printer.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.printer.setObjectName("printer")
        self.fileName = QtWidgets.QLabel(self.centralwidget)
        self.fileName.setGeometry(QtCore.QRect(260, 340, 291, 21))
        self.fileName.setMaximumSize(QtCore.QSize(16777215, 16777204))
        self.fileName.setStyleSheet("border: 1px solid; color: rgb(200,200,200);")
        self.fileName.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.fileName.setObjectName("fileName")
        self.choose = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.chooseFile())
        self.choose.setGeometry(QtCore.QRect(300, 400, 89, 25))
        self.choose.setObjectName("choose")
        self.select = QtWidgets.QPushButton(self.centralwidget, clicked= lambda : self.selectButtonAction())
        self.select.setGeometry(QtCore.QRect(430, 400, 89, 25))
        self.select.setObjectName("select")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Nova Slicer"))
        self.fileName.setText(_translate("MainWindow", "Select file"))
        self.choose.setText(_translate("MainWindow", "Choose"))
        self.select.setText(_translate("MainWindow", "Select"))

    def chooseFile(self):
        fname, _ = QtWidgets.QFileDialog.getOpenFileName(None,"Select 3D model", "","stl (*.stl);;STL(*.STL)")
        fileName = fname
        if (len(fname) > 35):
            fileName = "..." + fname[-37:]
        self.fileName.setText(fileName)
        self.filePath = fname

    def selectButtonAction(self):
        if(self.filePath != "" and self.filePath != None):
            Nova.Nova.closeButton(Nova, self.filePath)


